/**
 * Central tooltip string registry.
 * All tooltip text lives here — not hardcoded in components.
 */

export const RESOURCE_TOOLTIPS = {
  gold: (
    <>
      <strong style={{color:'#c8a048'}}>Gold</strong> — Your treasury.<br/>
      Earned from population income, Treasury building, and trade.<br/>
      Spent on troops, buildings, research, and crafting.
    </>
  ),
  food: (
    <>
      <strong style={{color:'#2a8a48'}}>Food</strong> — Feeds your troops.<br/>
      Earned from Farms and land. If food runs out, morale drops.<br/>
      Check the Military tab for your Food/hr drain.
    </>
  ),
  mana: (
    <>
      <strong style={{color:'#8830cc'}}>Mana</strong> — Arcane energy.<br/>
      Regenerates from Arcane Sanctum (+5%/lvl), Temple/Altar (+10%/lvl), and land.<br/>
      Used for spells and alchemy potions.
    </>
  ),
  industry: (
    <>
      <strong style={{color:'#c8d8e8'}}>Industry Points (IP)</strong> — Production capacity.<br/>
      Generated by Mine/Quarry (+8%/lvl).<br/>
      Required alongside Gold for building upgrades and crafting.
    </>
  ),
  land: (
    <>
      <strong style={{color:'#c8d8e8'}}>Land</strong> — Province size in acres.<br/>
      Gained by Exploring (1 AP = 5–25 ac) or Conquering enemies.<br/>
      More land = higher population cap and more resource production.
    </>
  ),
  ap: (
    <>
      <strong style={{color:'#c8a048'}}>Action Points</strong> — Your action budget.<br/>
      Max 20. Regenerates 1 every 30 minutes.<br/>
      Used for exploring, attacking, trading, researching, and casting spells.
    </>
  ),
};

export const PROVINCE_TOOLTIPS = {
  population: 'Grows over time from land and morale. More population = more gold income.',
  morale: 'Province happiness (0–100%). Drops when food runs out or you lose battles. Temple/Altar speeds recovery.',
  networth: 'Total value of your province — troops + buildings + land + resources. Used for leaderboard ranking.',
};

export const ATTACK_TOOLTIPS = {
  raid: 'Steal gold/resources. No land changes hands. Lowest casualties — best for farming inactive provinces. Costs 5 AP.',
  conquest: 'Capture 10–30% of enemy land. Medium casualties on both sides. Costs 5 AP.',
  raze: 'Destroy enemy buildings. Very high casualties. Best for crippling a dangerous rival. Costs 5 AP.',
  massacre: 'Kill enemy population. Extreme casualties. Reduces their long-term income. Costs 5 AP.',
  ap_cost: 'Costs 5 of your 20 AP. You regenerate 1 AP every 30 minutes.',
};

export const BUILDING_TOOLTIPS = {
  arcane_sanctum: 'Unlocks Tier 1 spells at L1, Tier 2 at L3, Tier 3 at L5. Essential for magic builds. +5% mana regen per level.',
  mine_quarry: 'Generates Industry Points for building upgrades. +8% IP per level.',
  barracks: 'Reduces training time 10%/lvl, increases max troop cap 5%/lvl.',
  watchtower: 'Reveals spies and attacks. +10% spy detect, +5% all defense per level.',
  war_hall: 'Unlocks T4 troops at L3, T5 troops at L5. Required for end-game military. +5% attack per level.',
  treasury: 'Increases gold storage cap and boosts passive income. +8% gold cap, +4% income per level.',
  walls: '+15% defense bonus per level. Very cost-effective for defensive players.',
  library: '-10% research time per level. Prioritize early if rushing techs.',
  marketplace_stall: 'Adds trade slots (+1 per level). Required to sell resources to other players.',
  temple_altar: 'Boosts mana regen (+10%/lvl) and speeds morale recovery (+5%/lvl).',
  farm: 'Boosts food production +5%/lvl. Critical when running a large army.',
  royal_bank: 'Human only. +15% gold income per level.',
  warchief_pit: 'Orc only. +10% troop attack per level.',
  crypt: 'Undead only. Raises skeleton troops from the dead after battle.',
  ancient_grove: 'Elf only. +15% mana regen and +10% land yield per level.',
  runic_forge: 'Dwarf only. +3 ATK/DEF bonus to Runic Warriors per level.',
};

export const MILITARY_TOOLTIPS = {
  atk: 'Attack power per troop. Total attack = sum of (qty × ATK) for all deployed troops.',
  def: 'Defense power per troop. Total defense = sum of (qty × DEF) for troops at home.',
  food_hr: 'Food consumed per hour by this troop type. Watch total Food/hr vs. your production.',
  train_time: 'Base time per troop. Reduced by Barracks level.',
  home: 'Troops available at home for defense and deployment.',
  training: 'Troops currently in the training queue.',
  deployed: 'Troops on an active attack mission — returning in 8 hours.',
};

export const CRAFTING_TOOLTIPS = {
  slots: 'Craft multiple potions simultaneously, one per slot. Upgrade Alchemist Tower for more slots.',
  tier: 'Tower tier unlocks higher-tier recipes. Tier 2 unlocks War Elixir, Plague Vial, and more. Tier 3 unlocks Berserker Brew and Mana Drain.',
};

export const SPELL_TOOLTIPS = {
  cooldown: 'Cannot be recast for this duration after use.',
  mana_cost: 'Mana is spent immediately on cast. Regenerates over time from Arcane Sanctum and Temple/Altar.',
};

export const RESEARCH_TOOLTIPS = {
  locked: 'Complete the prerequisite research first to unlock this tier.',
  ap_cost: 'Each research costs 1 AP + the listed gold. Gold is spent immediately; research completes after the listed time.',
};
